apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.admin.existingSecret }}
data:
  username: {{ b64enc .Values.adminusername | default "admin"}} # base64 encoding of user name 'admin-user'
  password: {{ b64enc .Values.adminpassword | default "admin"}} # base64 encoding of password 'admin-password'