# https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolume
apiVersion: v1
kind: PersistentVolume
metadata:
  {{- with first .Values.grafana.extraVolumes }}
  name: {{ .name }}
  {{- end }}
  labels:
    type: local
    {{- with first .Values.grafana.extraVolumes }}
    name: {{ .name }}
    {{- end }}
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: {{ .Values.hostpathMountingPathGrafanaPlugin }}
---
{{- range $index, $element := until (int .Values.grafana.replicas) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mounted-to-minikube-node-{{ $index }}
  labels:
    {{- toYaml $.Values.grafana.persistence.selectorLabels | nindent 4 }}
spec:
  storageClassName: {{ $.Values.grafana.persistence.storageClassName }} # Is required to be matched with the persistentvolumeclaimtemplate storageclassname
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ $.Values.hostPathMountingPersistentVolume }}/{{ $index }} # requires existing directory in minikube node where the local path is mounted (see minikube mount command)
---
{{- end }}