# Admin user name and password that is stored in a secret
adminusername: admin-user
adminpassword: admin-password

# Path on the host node in which the geomap wms panel is mounted via minikube mount command 
hostpathMountingPath: /geomap_wms

# ---------- this section overrides the grafana default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml ---------- #
## Expose the grafana service to be accessed from outside the cluster (LoadBalancer service).
## or access it from within the cluster (ClusterIP service). Set the service type and the port to serve it.
## ref: http://kubernetes.io/docs/user-guide/services/
##
grafana: # Since grafana is a subchart those variables must be in an object 'grafana' like the subcharts name: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart
  service:
    enabled: false
    type: NodePort
    port: 80
    targetPort: 3000
    portName: service
    nodePort: 30000

  useStatefulSet: true
  headlessService: true

  replicas: 2

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  persistence:
    type: statefulset # pvc
    enabled: true # false
    # existingClaim: task-pv-claim
    accessModes:
      - ReadWriteOnce

  ## Define command to be executed at startup by grafana container
  ## Needed if using `vault-env` to manage secrets (ref: https://banzaicloud.com/blog/inject-secrets-into-pods-vault/)
  ## Default is "run.sh" as defined in grafana's Dockerfile
  command:
    - "sh"
    - "/run.sh"

  # Use an existing secret for the admin user.
  admin:
    ## Name of the secret. Can be templated.
    existingSecret: admin-user-secret
    userKey: username
    passwordKey: password

  ## Pass the plugins you want installed as a list.
  plugins:
    - marcusolsson-json-datasource
    - iosb-sensorthings-datasource
    
  egress:
    ## @param networkPolicy.egress.enabled When enabled, an egress network policy will be
    ## created allowing grafana to connect to external data sources from kubernetes cluster.
    enabled: true

  grafana.ini:
    plugins:
      allow_loading_unsigned_plugins: geomap-wms-panel

  datasources:
    datasource.yaml:
      apiVersion: 1
      datasources:
        - name: FROST Internet
          type: iosb-sensorthings-datasource
          access: proxy
          url: https://geoportal-konfig-test.muenchen.de/frostk11/v1.1
          isDefault: false
        - name: JSON API FROST Internet
          type: marcusolsson-json-datasource
          access: proxy
          url: https://geoportal-konfig-test.muenchen.de/frostk11/v1.1
          isDefault: false
        - name: FROST Intranet
          type: iosb-sensorthings-datasource
          access: proxy
          url: https://geoportal-konfig-test2.muenchen.de/vis/v1.1
          isDefault: false
        - name: JSON API FROST Intranet
          type: marcusolsson-json-datasource
          access: proxy
          url: https://geoportal-konfig-test2.muenchen.de/vis/v1.1
          isDefault: false

  env:
    # Proxy-configuration for docker environment => minikube has to be deployed as docker container => set-driver to docker
    HTTP_PROXY: http://10.158.0.85:80
    HTTPS_PROXY: http://10.158.0.85:80
    NO_PROXY: http://grafana

  # Needs to be added to make available for extraVolumeMounts: https://github.com/grafana/helm-charts/blob/ec78147220603e8fba6c77ba4e2a13288edf67e3/charts/grafana/templates/_pod.tpl#L1250
  extraVolumes:
    - name: task-pv-claim-geomap-wms
      mountPath: /var/lib/grafana/plugins/geomap-wms-panel
      readOnly: true
      existingClaim: task-pv-claim-geomap-wms

  extraVolumeMounts:
    - name: task-pv-claim-geomap-wms
      mountPath: /var/lib/grafana/plugins/geomap-wms-panel
      readOnly: true
      existingClaim: task-pv-claim-geomap-wms
  
  # Extra init container to create directory to mount geomap-plugin into containers
  extraInitContainers:
  - name: create-geomap-wms-panel-dir
    image: "docker.io/library/busybox:1.31.1"
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add:
          - CHOWN
      runAsNonRoot: false
      runAsUser: 0
      seccompProfile:
        type: RuntimeDefault
    command:
      - /bin/mkdir
      - -p
      - --mode=777
      - /var/lib/grafana/plugins/geomap-wms-panel
    volumeMounts:
      - name: storage
        mountPath: "/var/lib/grafana"
# ---------- end of section thet overrides the grafana default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml ---------- #