name: e2e
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  e2e:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install node modules
      run: npm install
    - run: npm run build
      name: Build the plugin
    - name: Run docker compose
      run: docker compose up -d
    - name: Check if Grafana is ready
      run: | 
        while [[ "$(curl --insecure -s -o /dev/null -w "%{response_code}" http://localhost:3000/api/health)" != "200" ]]; do 
            sleep 1
        done
    - name: Run e2e tests with cypress
      run: npm run e2e
    
