name: Playwright Tests
on:
  workflow_call: # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - run: npm run build
      name: Build the plugin
    - name: Run docker compose
      run: docker compose up -d
    - name: Check if Grafana is ready
      run: | 
        while [[ "$(curl --insecure -s -o /dev/null -w "%{response_code}" http://localhost:3000/api/health)" != "200" ]]; do 
            sleep 1
            echo "Grafana server not ready."
        done
        echo "Grafana server ready to accept connections."
    - name: Run Playwright tests
      id: run-tests
      run: npm run e2e
      env:
        CI: 'true' # https://playwright.dev/docs/ci
    - uses: actions/upload-artifact@v4
      if: ${{ (always() && steps.run-tests.outcome == 'success') || (failure() && steps.run-tests.outcome == 'failure') }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
